version: "3.4"

services:
    char-image:
        image: char-image
        build: .
        environment:
            NODE_ENV: production
            PORT: 3201
        ports:
            - 3201:3201
