version: '3.4'

services:
  char-image:
    image: char-image
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3201
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./bin/www